### ISSUE TITLE
Update UI: Stock Page

### ISSUE THREAD

**Issue by Zachary-Harrison** [Zachary-Harrison/cs3450-group10#107]
This is where the manager sees a list of ingredients in their store and how much there is left. 
Story Points: 0.75

**Comment by noahjknight** [comment]
UI has been completed.  Took 0.75 hours.  Completed 11/3/2022.

**Comment by noahjknight** [comment]
Finished 11/8/2022 @ 12:36PM.  Took approx. 1 hour
