### ISSUE TITLE
Hookup Buttons: Find Buttons

### ISSUE THREAD

**Issue by Zachary-Harrison** [Zachary-Harrison/cs3450-group10#113]
Find all the buttons that need hooking up. 
Story points: 0.5

**Comment by noahjknight** [comment]
Remaining buttons to work on.

Place Order For Self
Place Order for Customer
Fulfill Order

**Comment by noahjknight** [comment]
Completed All Buttons.  Finished 11/12/2022 @ 1:.30 PM
