### ISSUE TITLE
Creating Users: encryption/decryption

### ISSUE THREAD

**Issue by Zachary-Harrison** [Zachary-Harrison/cs3450-group10#38]
Use the Django methods that encrypt/decrypt passwords.
Story points: 0.25

**Comment by thatsmellything** [comment]
Took about 3 hours, October 5th
Finished with Todo #37  
commit https://github.com/Zachary-Harrison/cs3450-group10/commit/0c013bad8add728e18658c5cc05c64f073c6c1a6
