### ISSUE TITLE
Ingredients UI

### ISSUE THREAD

**Issue by Zachary-Harrison** [Zachary-Harrison/cs3450-group10#73]
This is the user interface for a manager to update the store's database of ingredients
Story Points: 0.75

**Comment by noahjknight** [comment]
Began working on this.  So far, has taken between 0.25 and 0.5 hours

**Comment by noahjknight** [comment]
Finished basic UI on 10/27/2022 @ 10:15AM.  Took approx. 0.75 hours total.
